(function(){
"use strict";
var app=document.getElementById("app");
var state={user:null,page:"dashboard"};
var SESSION_MS=180000,expires=0,timer=null;
var USERS={
 admin:{password:"Admin2026!",nickname:"Nikita_Zvezda",position:"Руководство",role:"management"},
 test:{password:"Test2026!",nickname:"Test_Admin",position:"Модератор",role:"admin"}
};
var ADMINS=[
 {nickname:"Nikita_Zvezda",position:"Руководство"},
 {nickname:"Test_Admin",position:"Модератор"},
 {nickname:"Alex_Murmansk",position:"Старший модератор"},
 {nickname:"Max_Admin",position:"Администратор"},
 {nickname:"Rus_Leader",position:"Следящий"}
];
var POSITIONS=["Младший модератор","Модератор","Старший модератор","Администратор","Старший администратор","Следящий","Старший следящий","Следящий за силовыми организациями","Старший следящий за силовыми организациями"];
function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;")}
function get(k,d){try{var v=localStorage.getItem(k);return v===null?d:v}catch(e){return d}}
function set(k,v){try{localStorage.setItem(k,v)}catch(e){}}
function norms(){try{var v=JSON.parse(get("br_normatives","[]"));return Array.isArray(v)?v:[]}catch(e){return[]}}
function toast(t){var x=document.querySelector(".toast");if(x)x.remove();x=document.createElement("div");x.className="toast";x.textContent=t;document.body.appendChild(x);setTimeout(function(){if(x.parentNode)x.remove()},2200)}
function reset(){if(!state.user)return;expires=Date.now()+SESSION_MS;set("br_session",JSON.stringify({user:state.user,expires:expires}));tick()}
function logout(){state.user=null;expires=0;set("br_session","");if(timer)clearInterval(timer);timer=null;render()}
function tick(){var e=document.getElementById("sessionTimer"),c=document.getElementById("sessionCard");if(!state.user)return;var s=Math.max(0,Math.ceil((expires-Date.now())/1000)),m=Math.floor(s/60),r=String(s%60).padStart(2,"0");if(e)e.textContent="Сессия: "+m+":"+r;if(c)c.textContent=m+":"+r}
function startTimer(){if(timer)clearInterval(timer);timer=setInterval(function(){if(!state.user)return;if(Date.now()>=expires){toast("Сессия истекла");logout();return}tick()},1000);tick()}
["click","keydown","touchstart","pointerdown","scroll"].forEach(function(n){document.addEventListener(n,function(){if(state.user)reset()},{passive:true})});
function login(l,p){var a=USERS[String(l).trim().toLowerCase()];if(!a||a.password!==p)return false;state.user={nickname:a.nickname,position:a.position,role:a.role};state.page="dashboard";reset();startTimer();render();return true}
function nav(p){if(p==="normatives"&&state.user.role==="management"){toast("Руководству отправка нормативов не требуется");return}state.page=p;render()}
var eyeOpen='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"></path><circle cx="12" cy="12" r="2.8"></circle></svg>';
var eyeClosed='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 3l18 18"></path><path d="M10.6 5.2A10.7 10.7 0 0 1 12 5c6 0 9.5 7 9.5 7a17 17 0 0 1-3.1 3.7M6.2 6.2C3.8 8.2 2.5 12 2.5 12s3.5 6 9.5 6c1.5 0 2.8-.4 4-1"></path><path d="M9.9 9.9a2.8 2.8 0 0 0 4.2 4.2"></path></svg>';
function renderLogin(){app.innerHTML='<div class="login-page"><div class="login-card"><div class="login-brand"><div class="logo">BR</div><div class="brand-text"><strong>BLACK RUSSIA</strong><span>Мурманск • Admin Panel</span></div></div><h1>Авторизация</h1><p>Войдите в панель администрации сервера.</p><form class="login-form" id="loginForm"><div class="field"><label>Логин</label><input id="login" autocomplete="username" required></div><div class="field"><label>Пароль</label><div class="password-box"><input id="password" type="password" autocomplete="current-password" required><button type="button" id="passwordToggle" class="password-eye" aria-label="Показать пароль" title="Показать пароль">'+eyeOpen+'</button></div></div><div id="loginError" class="error"></div><button class="button button-primary" type="submit">Войти</button><div class="demo-credentials"><strong>Тестовые данные</strong><span>admin / Admin2026!</span><span>test / Test2026!</span></div></form></div></div>';
var input=document.getElementById("password"),button=document.getElementById("passwordToggle");button.addEventListener("click",function(){var v=input.type==="text";input.type=v?"password":"text";button.innerHTML=v?eyeOpen:eyeClosed;button.setAttribute("aria-label",v?"Показать пароль":"Скрыть пароль")});document.getElementById("loginForm").addEventListener("submit",function(e){e.preventDefault();var ok=login(document.getElementById("login").value,document.getElementById("password").value);if(!ok)document.getElementById("loginError").textContent="Неверный логин или пароль"})}
function navButton(p,i,t){return '<button class="nav-button'+(state.page===p?' active':'')+'" data-page="'+p+'"><span class="nav-icon">'+i+'</span><span>'+t+'</span></button>'}
function sidebar(){var m=state.user.role==="management";return '<aside class="sidebar"><div class="brand"><div class="logo">BR</div><div class="brand-text"><strong>BLACK RUSSIA</strong><span>Мурманск • Admin Panel</span></div></div><nav class="nav"><div class="nav-section">ПАНЕЛЬ</div>'+navButton("dashboard","⌂","Главная")+navButton("profile","◉","Мой профиль")+(m?navButton("admins","♟","Состав администрации"):navButton("normatives","↑","Нормативы"))+(m?navButton("normatives-all","▣","Нормативы"):"")+'</nav><div class="sidebar-bottom"><div class="profile"><div class="avatar">'+esc(state.user.nickname.slice(0,2).toUpperCase())+'</div><div class="profile-text"><strong>'+esc(state.user.nickname)+'</strong><span>'+esc(state.user.position)+'</span></div></div><button class="button button-danger" id="logoutButton" style="width:100%;margin-top:8px">Выйти</button></div></aside>'}
function topbar(){return '<header class="topbar"><div class="topbar-left"><button class="button button-icon mobile-menu-button" id="menuButton">☰</button><span class="topbar-title">АДМИНИСТРАЦИЯ • МУРМАНСК</span></div><div class="topbar-right"><span id="sessionTimer" class="topbar-title"></span></div></header>'}
function head(t,s){return '<div class="page-head"><div class="page-head-main"><h1>'+esc(t)+'</h1><p>'+esc(s)+'</p></div></div>'}
function watermark(){return '<div class="watermark" aria-hidden="true">'+esc(state.user.nickname)+'</div>'}
function dashboard(){return head("Добро пожаловать","Личный кабинет администрации Black Russia • Мурманск")+'<div class="grid stats-grid"><div class="stat-card"><span class="stat-label">НИКНЕЙМ</span><strong class="stat-value">'+esc(state.user.nickname)+'</strong></div><div class="stat-card"><span class="stat-label">ДОЛЖНОСТЬ</span><strong class="stat-value">'+esc(state.user.position)+'</strong></div><div class="stat-card"><span class="stat-label">СТАТИСТИКА</span><strong class="stat-value">Временно отключена</strong></div><div class="stat-card"><span class="stat-label">СЕССИЯ</span><strong class="stat-value" id="sessionCard">3:00</strong></div></div><div class="grid split-grid"><div class="card"><div class="card-head"><h2>Доступ</h2><span>'+(state.user.role==="management"?"Руководство":"Администратор")+'</span></div><div class="notice">Статистика временно отключена. Сейчас используются только никнейм и должность.</div></div><div class="card"><div class="card-head"><h2>Безопасность</h2><span>Сессия</span></div><p style="color:var(--muted);font-size:11px;line-height:1.6;margin:0">Таймер автоматически продлевается при активности. При отсутствии активности в течение 3 минут произойдёт выход.</p></div></div>'}
function profile(){return head("Мой профиль","Данные текущего администратора")+'<div class="card"><div class="form-grid"><div class="field"><label>Никнейм</label><input value="'+esc(state.user.nickname)+'" readonly></div><div class="field"><label>Должность</label><input value="'+esc(state.user.position)+'" readonly></div></div></div>'}
function normatives(){var h=norms().filter(function(x){return x.nickname===state.user.nickname});var rows=h.length?h.map(function(x){return '<tr><td>'+esc(x.date)+'</td><td>'+esc(x.position)+'</td><td>'+esc(x.file)+'</td><td>'+esc(x.comment||"—")+'</td></tr>'}).join(""):'<tr><td colspan="4">Нормативы пока не отправлялись.</td></tr>';return head("Нормативы","Отправка файла с датой, должностью и комментарием")+'<div class="card"><form id="normativeForm"><div class="form-grid"><div class="field field-full"><label>Файл</label><div class="file-box"><input id="normativeFile" type="file" required><div id="fileInfo" class="file-info">Файл не выбран</div></div></div><div class="field"><label>Дата</label><input id="normativeDate" type="date" required value="'+new Date().toISOString().slice(0,10)+'"></div><div class="field"><label>Должность</label><select id="normativePosition">'+POSITIONS.map(function(p){return '<option>'+esc(p)+'</option>'}).join("")+'</select></div><div class="field field-full"><label>Комментарий</label><textarea id="normativeComment" placeholder="Комментарий к нормативу"></textarea></div></div><div style="margin-top:15px"><button class="button button-primary" type="submit">Сохранить норматив</button></div></form></div><div class="card" style="margin-top:15px"><div class="card-head"><h2>Мои нормативы</h2><span>локально</span></div><div class="table-wrapper"><table><thead><tr><th>Дата</th><th>Должность</th><th>Файл</th><th>Комментарий</th></tr></thead><tbody>'+rows+'</tbody></table></div></div>'}
function admins(){return head("Состав администрации","Публичный список никнеймов и должностей")+'<div class="card"><div class="table-wrapper"><table><thead><tr><th>Никнейм</th><th>Должность</th></tr></thead><tbody>'+ADMINS.map(function(a){return '<tr><td>'+esc(a.nickname)+'</td><td>'+esc(a.position)+'</td></tr>'}).join("")+'</tbody></table></div></div>'}
function normativeAll(){var l=norms();var r=l.length?l.map(function(x){return '<tr><td>'+esc(x.nickname)+'</td><td>'+esc(x.date)+'</td><td>'+esc(x.position)+'</td><td>'+esc(x.file)+'</td><td>'+esc(x.comment||"—")+'</td></tr>'}).join(""):'<tr><td colspan="5">Отправленных нормативов нет.</td></tr>';return head("Нормативы администрации","Локальный журнал отправленных нормативов")+'<div class="card"><div class="table-wrapper"><table><thead><tr><th>Никнейм</th><th>Дата</th><th>Должность</th><th>Файл</th><th>Комментарий</th></tr></thead><tbody>'+r+'</tbody></table></div></div>'}
function content(){if(state.page==="profile")return profile();if(state.page==="normatives")return normatives();if(state.page==="admins")return admins();if(state.page==="normatives-all")return normativeAll();return dashboard()}
function bind(){document.querySelectorAll("[data-page]").forEach(function(b){b.addEventListener("click",function(){nav(b.getAttribute("data-page"))})});var l=document.getElementById("logoutButton");if(l)l.addEventListener("click",logout);var menu=document.getElementById("menuButton");if(menu)menu.addEventListener("click",function(){var s=document.querySelector(".sidebar");if(s)s.classList.toggle("mobile-open")});var f=document.getElementById("normativeForm");if(f){var fi=document.getElementById("normativeFile");fi.addEventListener("change",function(){var x=fi.files[0];document.getElementById("fileInfo").textContent=x?x.name+" • "+Math.ceil(x.size/1024)+" КБ":"Файл не выбран"});f.addEventListener("submit",function(e){e.preventDefault();var x=fi.files[0];if(!x)return;var a=norms();a.unshift({nickname:state.user.nickname,date:document.getElementById("normativeDate").value,position:document.getElementById("normativePosition").value,comment:document.getElementById("normativeComment").value.trim(),file:x.name});set("br_normatives",JSON.stringify(a.slice(0,50)));toast("Норматив сохранён локально");render()})}}
function render(){if(!state.user){renderLogin();return}app.innerHTML='<div class="app">'+sidebar()+'<main class="main">'+topbar()+'<section class="content">'+content()+'</section></main>'+watermark()+'</div>';bind();tick()}
function restore(){try{var s=JSON.parse(get("br_session",""));if(s&&s.user&&s.expires>Date.now()){state.user=s.user;expires=s.expires;startTimer();return true}}catch(e){}return false}
if(!restore())render();
})();
